### ISSUE TITLE
OSX: ✖ Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by DmytroShtanko1** [blueimp/nightwatch-video-recorder#1]
```
✖ Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

FAILED:  1 errors (321ms)

 _________________________________________________

 TEST FAILURE: 1 error during execution,  0 assertions failed, 0 passed. (449ms)


 × portal_main_page

   - Displaying the items of main page (321ms)

     Error while running [Portal Main Page / Displaying the items of main page]:


     Error: spawn ffmpeg ENOENT
       at exports._errnoException (util.js:1026:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)

       at onErrorNT (internal/child_process.js:359:16)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9)



Error retrieving a new session from the selenium server


```
Hi guys, have had an error when  did everything according to the instructions

**Comment by shripadbothaleAvalara** [comment]
I am also getting same kind of error
Error: spawn ffmpeg ENOENT
       at exports._errnoException (util.js:1026:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:359:16)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9)
Is there any other dependencies that need to be installed (I am using Mac os)

**Comment by amrittsingh-zz** [comment]
Did anyone Resolve this issue.. I am facing the same Issue ...

**Comment by timrsfo** [comment]
I am getting this also, I'm running on a MAC.
If you add --verbose to your test run do you get the following:

    Error: Command failed: ffmpeg -video_size 1440x900 -r 15 -f x11grab -i 127.0.0.1:60 -pix_fmt 
    yuv420p -loglevel error /Users/my-path/xyzTest-2017-07-31T03-33-56.mp4
    Unknown input format: 'x11grab'
        at ChildProcess.exithandler (child_process.js:204:12)
        at maybeClose (internal/child_process.js:886:16)
        at Socket.<anonymous> (internal/child_process.js:342:11)
        at Pipe._handle.close [as _onclose] (net.js:497:12)
    at ChildProcess.exithandler (child_process.js:204:12)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

I think it might have something to do with x11grab on the MAC
https://github.com/Homebrew/legacy-homebrew/issues/17641

> According to the following instructions ffmpeg under OSX should really use avfoundation device instead of x11grab, so as long as you adapt your ffmpeg command line option to pass in a different -f argument as well as -i with the proper format depending on what environment you're running on (Linux or OSX), anyone attempting to use x11grab under OSX should be good to go, so I guess no work is needed from Homebrew after all.

[ffmpeg OSX](https://trac.ffmpeg.org/wiki/Capture/Desktop)

> Use the avfoundation device:
ffmpeg -f avfoundation -list_devices true -i ""
This will enumerate all the available input devices including screens ready to be captured.
Once you've figured out the device index corresponding to the screen to be captured use:
ffmpeg -f avfoundation -i "<screen device index>:<audio device index>" out.mov
This will capture the screen from <screen device index> and audio from <audio device index> into the output file out.mov.

... Still haven't figured this out, but hope this helps

**Comment by timrsfo** [comment]
I was able to run the following command from the command line: 

    ffmpeg -video_size 1440x900 -r 15 -f avfoundation -i "1" -pix_fmt nv12 -loglevel error ./my_outputfile.mp4

and open it with quicktime. May be able to get this to work if there the -f option was brought out to the videos { } in nightwatch.json

**Comment by timrsfo** [comment]
looks like some errors can be ignored, so if you set loglevel to fatal things work a bit better
ffmpeg -video_size 1440x900 -r 15 -f avfoundation -i 1 -pix_fmt nv12 -loglevel fatal 
I'm still unable to get ffmpeg to close on test completion

**Comment by blueimp** [comment]
Sorry for the late reply.
I've tested this code originally on OSX and Linux, but we're only using it on Linux, specifically as part of this Docker setup:
https://github.com/blueimp/nightwatch

I'm open to pull requests, but as of now, OSX is basically unsupported.

**Comment by aamorozov** [comment]
@timrsfo 
I'm using it on mac, and the only thing I needed to do additionally is 
```brew install ffmpeg```. 
All other things worked for me out of the box

**Comment by rodrigogiraudo** [comment]
> @timrsfo
> I'm using it on mac, and the only thing I needed to do additionally is
> `brew install ffmpeg`.
> All other things worked for me out of the box

This solves every problem I Had. It installs tons of dependencies but works
