### ISSUE TITLE
OS X Support?

### ISSUE THREAD

**Issue by achingbrain** [blueimp/nightwatch-video-recorder#2]
This looks like a really neat module but when I try to run this on OS X, ffmpeg bails because it doesn't understand the input format 'x11grab':

```
 ✖ Error: Command failed: ffmpeg -video_size 1440x900 -r 15 -f x11grab -i localhost:60 -pix_fmt yuv420p -loglevel error /blah/blah/tests-2017-03-04T08-49-16.mp4
Unknown input format: 'x11grab'

    at ChildProcess.exithandler (child_process.js:206:12)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by blueimp** [comment]
Please see https://github.com/blueimp/nightwatch-video-recorder/issues/1#issuecomment-325231629

Closing this as duplicate.
